# Generated by Django 4.2.1 on 2023-06-23 19:48

from django.db import migrations
import flashcard2.models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard2', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', flashcard2.models.UserManager()),
            ],
        ),
    ]
